version: "3.9"
services:
  backend:
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile
    ports:
      - "8000:8000"
  mongo:
    image: "mongo:5.0.8-focal"
    restart: always
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:


